### ISSUE TITLE
Kotlin: function names are not highlighted

### ISSUE THREAD

**Issue by rongi** [jneen/rouge#792] opened 2017-10-04 08:13 UTC
Example:
http://rouge.jneen.net/pastes/w8Wg

Note how function name is gray. Usually rouge highlights function names with another color. Compare with this Java example:

http://rouge.jneen.net/pastes/Mak3

I believe this is a regression of this:
#782

**Comment by lordcodes** [comment] 2018-09-19 21:49
They are being highlighted as 'Name', but they should be 'Name.Function' I think. Currently, you cannot colour them separately, as it would resulting in lots of other stuff being re-coloured as well.

**Comment by lordcodes** [comment] 2018-09-20 17:48
I believe this issue was caused by #782 @gfx. I rolled back the rouge gem to 2.2.1 just before that PR was merged and Kotlin functions are correctly highlighted. However, now they are no longer highlighted and just show as regular 'Name' tokens.

**Closed** 2018-10-01 15:39 UTC
Labels: bug
