### ISSUE TITLE
Where is the support for ES6 / Babel / JSX?

### ISSUE THREAD

**Issue by madhur** [jneen/rouge#475] opened 2016-05-27 19:42 UTC
Would love to have highlighting for ES6 / Babel / JSX code.

**Comment by connorshea** [comment] 2016-06-01 23:25
This is a duplicate of #275 (JSX) and #432 (ES6).

**Comment by jneen** [comment] 2016-06-01 23:49
ah yep. closing as duplicate.

**Closed** 2016-06-01 23:50 UTC
Labels: duplicate, enhancement
