### ISSUE TITLE
Include support for Nix Expression Highlighting

### ISSUE THREAD

**Issue by KelvinMutuma** [jneen/rouge#406] opened 2016-02-26 08:47 UTC
Here is a sample: https://gitlab.com/fractalide/fractalide/blob/master/build-support/buildFractalideComponent.nix

**Comment by phunehehe** [comment] 2016-03-28 03:30
This seems to be a duplicate of https://github.com/jneen/rouge/issues/345 (mine :))

**Comment by jneen** [comment] 2016-07-12 21:39
Closed as duplicate of #345. Thanks!

**Closed by jneen** 2016-07-12 21:39 UTC
